# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Experience
    url: /#experience
    weight: 10
  - name: Blog
    url: /blog/
    weight: 20
  - name: Library
    url: /library/
    weight: 30
  - name: Computers
    url: /computers/
    weight: 40
  - name: Contact
    url: /#contact
    weight: 50
