export default {
  currentYear: new Date().getUTCFullYear(),
  name: "Ben Sampica",
  legalName: "Blueprint Software",
  url: "https://www.bensampica.com",
  language: "en-US",
  description:
    "Software engineer, consultant, and writer covering .NET, architecture, testing, and software craftsmanship.",
  tagline: "Founder - Blueprint Software",
  email: "benjamin.sampica@gmail.com",
  bio: [
    "Software engineer, consultant, and writer focused on pragmatic systems, durable delivery, and the craft of building software with other people.",
    "I spend most of my time working in .NET, cloud architecture, testing, and DevOps. Outside of work I read, build PCs, and run Dungeons & Dragons campaigns.",
  ],
  navigation: [
    { label: "Experience", url: "/#experience" },
    { label: "Blog", url: "/blog/" },
    { label: "Library", url: "/library/" },
    { label: "Computers", url: "/computers/" },
    { label: "Contact", url: "/#contact" },
  ],
  social: [
    { label: "Email", url: "mailto:benjamin.sampica@gmail.com", icon: "email" },
    { label: "Resume", url: "/uploads/resume.pdf", icon: "document" },
    { label: "GitHub", url: "https://github.com/benjaminsampica", icon: "github" },
    { label: "LinkedIn", url: "https://www.linkedin.com/in/benthon", icon: "linkedin" },
    { label: "Bluesky", url: "https://bsky.app/profile/bensampica.com", icon: "bluesky" },
  ],
  experience: [
    {
      role: "Founder",
      company: "Blueprint Software",
      url: "https://www.blueprint.software",
      location: "Ankeny, IA",
      start: "2025-01-01",
    },
    {
      company: "Casey's General Stores",
      url: "https://www.caseys.com",
      location: "Ankeny, IA",
      start: "2021-12-20",
      end: "2025-05-01",
      roles: [
        {
          role: "Lead Software Engineer",
          start: "2024-06-01",
          end: "2025-05-01",
        },
        {
          role: "Senior Software Engineer",
          start: "2021-12-20",
          end: "2024-06-01",
        },
      ],
    },
    {
      role: "Software Engineer III",
      company: "Comoto Holdings, Inc.",
      url: "https://ridecomoto.com/",
      location: "Philadelphia, PA",
      start: "2021-06-28",
      end: "2021-11-28",
    },
    {
      role: "Senior Application Developer",
      company: "Homesteaders Life Company",
      url: "https://www.homesteaderslife.com/",
      location: "Des Moines, IA",
      start: "2020-08-17",
      end: "2021-06-28",
    },
    {
      role: "Web Application Developer",
      company: "Polk County",
      url: "https://www.polkcountyiowa.gov",
      location: "Des Moines, IA",
      start: "2019-08-21",
      end: "2020-08-14",
    },
    {
      role: "Software Engineer",
      company: "Casey's General Stores",
      url: "https://www.caseys.com",
      location: "Ankeny, IA",
      start: "2019-03-16",
      end: "2019-08-21",
    },
    {
      role: "Associate Web Developer",
      company: "Polk County",
      url: "https://www.polkcountyiowa.gov",
      location: "Des Moines, IA",
      start: "2016-06-26",
      end: "2019-03-16",
    },
  ],
  computerImages: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21],
};
